# Generated by Django 5.0 on 2023-12-14 02:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_instructor_assignment_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
