# Generated by Django 5.0 on 2023-12-16 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_submission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
